import BackgroundAnimation from "@/components/BackgroundAnimation/BackgroundAnimation";
import Hero from "@/components/Hero/Hero";
import Projects from "@/components/Projects/Projects";
import Layout from "@/layout/Layout";
import { Section } from "@/themes/GlobalComponents";
import Head from "next/head";

export default function Home() {
    return (
        <>
        <Layout>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Section grid>
                <Hero/>
                <BackgroundAnimation/>
            </Section>
            <Projects/>
        </Layout>
        </>
    )
}
